CodeGra-de/CodeGra.de

src/components/CGIgnoreFile.vue

Add the Ctrl-Enter keybinding on the .cg-ignore field, this closes #301.

Add the Ctrl-Enter keybinding on the .cg-ignore field

---

.travis.yml
src/components/AssignmentState.vue
src/components/ManageAssignment.vue

Fix assignment state buttons for LTI assignment (#367)

Release FlipFloppedWhiteSocked patch 1

---

src/components/SubmissionList.vue

Store submissions filter on any keyup, not just enter

---

src/components/GradeViewer.vue
src/components/RubricViewer.vue

This also fixes problems with the out of sync message.

Make long rubric item headers show an ellipsis

---

src/components/FileViewer.vue
src/components/InnerCodeViewer.vue

* Reset error in the FileViewer when the file changes
* Remove InnerCodeViewer hack

Release hotfix JungleJoy.1.1

---

.travis.yml
docs/guides/use-codegrade-as-a-student.rst
docs/index.rst
psef/auto_test/__init__.py
psef/exceptions.py
psef/models/rubric.py
psef/v1/assignments.py
psef_test/test_auto_test.py
src/components/AutoTest.vue
src/components/AutoTestRun.vue
src/components/AutoTestSet.vue
src/components/RubricEditor.vue
src/components/RubricViewer.vue
src/components/SubmitButton.vue
src/pages/ManageAssignment.vue

* Fix issues with the rubric editor when AutoTest was used. (#1061)
* Fix issues with AutoTest runners never starting. (#1065)

Release hotfix JungleJoy.2.1

---

psef/auto_test/__init__.py
src/components/AutoTestStep.vue
src/models/auto_test.js
src/utils/diff.js
test/unit/specs/diff.spec.js

* Fix very long waiting on attach (#1081)
* Count the achieved points of capture_points steps in suite percentage (#1080)

Release hotfix JungleJoy.2.3

---

src/components/GradeViewer.vue
src/components/RubricEditorNormalRow.vue
src/components/RubricViewer.vue
src/components/RubricViewerContinuousRow.vue
src/components/RubricViewerNormalRow.vue

* Fix GradeViewer not displaying the fixed max rubric points when it's set.
* Fix RubricViewer item background colors on hover/selected.
* Fix rubric row & item description max height in the RubricViewer.

Release hotfix version Knoet.2.1

---

src/models/submission.js

* Copy the `comment` (general feedback) over to an instance of the Submission model from the server data, so it gets displayed correctly.

Release version Knoet.2.3

---

src/main.js

This makes it easier (/possible) to see if a deadline is in 24 hours or 36.
DEV-125 #finished

[DEV-125] Update threshold when relative time starts using days

---

.eslintrc.js
cypress/integration/tests/home-grid.spec.js
cypress/integration/tests/submission-uploader.spec.js
cypress/support/commands.js
src/components/HomeGrid.vue
src/utils/counter.js
src/utils/index.js
test/unit/specs/util.spec.js

This changes three things:
- Add infinite loader to home grid: This makes the initial render much master, especially when you have a lot of courses.
- Improve sorting on the HomeGrid: This sorts from new to old courses, and if the creation date is exactly the same we sort based on name.
-  Add year or full date to course names when there are duplicates.
DEV-52 #finished
DEV-53 #finished

[DEV-52 DEV-53] Improve the UX of the HomeGrid

---

src/components/GradeViewer.vue
src/components/SubmissionNavBar.vue
src/pages/Submission.vue

* Fix detection of old submission by user in group (#1297)

Release hotfix Knoet.3.1

---

cypress/integration/tests/manage-course.spec.js
src/components/StudentContact.vue
src/components/SubmissionsExporter.vue
src/components/UserNotification.vue
src/components/UsersManager.vue
src/my-vue.ts
src/pages/Submission.vue
src/utils/index.js
src/utils/typed.ts
test/unit/specs/util.spec.js

This function automatically encodes all parts of the url.

Fix url encoding in various places by adding `buildUrl` function

---

src/components/Linter.vue

Fixes another instance of [FRONTEND-A](https://cg-sentry-db43058bf52088bb7a3b6.codegra.de/organizations/codegrade/issues/72/events/bf69762b3b02477c856cd3fe332f8f2f/?project=3)

Catch 404 in Linter.vue

---

src/components/FeedbackReply.vue

DEV-192 Fix snippet popover size

---

.github/scripts/ensure_changelog_updated.sh
.github/scripts/ensure_file_changed.sh
.github/workflows/changelog.yml

Add github action to check if the changelog was updated

---

.github/scripts/run_linters.bash
README.md
docs/conf.py

Improve docs and readme

---

migrations/versions/bef732f2f4ac_.py

The problem was that we assumed that "users-courses.course_id" is a course
id (as the name suggests), however it is *not*. It is a course role id, and we
forgot to join the course role before going to the course. This commit fixes
that, and it also fixes the issue when a user was already connected to multiple
LTI 1.1 providers that it would only be connected to a single one after the
migration. This is fixed by simple getting all LTI courses that a user is
enrolled in and adding the lti provider ids for each of these courses (after
filtering out duplicate lti course ids of course).

Fix LTI 1.3 migration

---

.github/scripts/run_linters.bash
README.md
docs/about/changelog.rst
docs/conf.py
migrations/versions/bef732f2f4ac_.py
src/components/InnerIPythonViewer.vue
src/utils/ipython.ts
test/unit/specs/IPythonViewer.spec.js

* Improve docs and readme (#1365)
* Fix LTI 1.3 migration (#1366)
* Fix ipython execute_result output (#1367)

Release hotfix LowVoltage.1.1

---

docs/about/changelog.rst
src/components/AutoTestStep.vue
src/components/AutoTestSuite.vue
src/components/FileRule.vue
src/components/FileUploader.vue
src/components/ForgotPassword.vue
src/components/HomeGrid.vue
src/components/HtmlViewer.vue
src/components/Login.vue
src/components/MultipleFilesUploader.vue
src/components/RubricViewerContinuousRow.vue
src/components/SnippetManager.vue
src/components/SnippetableInput.vue
src/components/UsersManager.vue
src/main.js

DEV-198 Automatically focus continuous row input

---

psef/models/lti_provider.py
src/components/LtiProviderSetup/CanvasSetup.vue

The json config was incorrect, and the setup also used the wrong value for the
key set url.

Fix Canvas LTI 1.3 setup

---

src/components/SubmitInput.vue

DEV-22 Automatically focus new course/assignment name input

---

cg_cache/tests/test_inter_request.py
docs/about/changelog.rst
psef/archive.py
psef_test/test_generated_files.py

DEV-76 Add trailing newline to symlink replacement files

---

docs/about/changelog.rst
src/components/HomeGrid.vue
src/components/Sidebar/CourseList.vue
src/components/Sidebar/CourseListItem.vue

DEV-195 Add year to course names in the sidebar if other courses with same name exist

---

.github/scripts/run_integration.bash
build/webpack.dev.conf.js
cypress/integration/tests/submission.spec.js
docs/about/changelog.rst
psef/v1/auto_tests.py
psef/v_internal/auto_tests.py
src/components/DiffOverview.vue
src/components/FeedbackReply.vue
src/components/FileRule.vue
src/components/GradeViewer.vue
src/components/InnerCodeViewer.vue
src/components/JunitResult.vue
src/components/NotificationSettings.vue
src/components/PeerFeedbackAssessment.vue
src/components/PeerFeedbackSettings.vue
src/components/SnippetableInput.vue
src/my-vue.ts

* Fix Junit XML view when test has no cases or suites
* Hide peer feedback assessment component for non peer feedback replies
* Fix clicking on snippet to select  a snippet
* Fix background for notification settings in dark mode

Release Mosaic bugfixes

---

src/components/FeedbackOverview.vue

The filename header in the feedback overview used the light mode background in dark mode.
DEV-238 #done

DEV-238 Fix dark mode issues

---

docs/about/changelog.rst
src/components/AnalyticsSubmissionDate.vue

DEV-241 Remove "years" option from the "submitted on" graph

---

src/models/auto_test.js

Fix typo in AutoTest suite validation error message

---

src/components/AssignmentGeneralSettings.vue

- Fix setting general assignment settings for LTI 1.1 assignments (#1443)

 Release hotfix Mosaic.1.1

---

src/components/LtiProviderSetup/CanvasSetup.vue

Admins don't know when they should use this, so it is better not to offer it and
simply manually update the database if necessary (which is approx. never).

Remove Canvas advanced options section

---

src/components/SubmissionList.vue

This also uses the uses the `v-debounce` directive on the `<submit>` of the submission list rather than our hand-rolled method (which was broken because we did not clear the timer correctly).
DEV-287 #done

DEV-287 Do not jump back to first page of submissions when changing assignee
