src/components/Sidebar/index.vue
#451 introduced a bug that the sidebar didn't drop a shadow on the page when more than one submenu level was open.
=> Fix sidebar shadow with more than one submenu level

psef/auto_test/__init__.py, psef_test/test_auto_test.py, src/components/AssignmentState.vue, src/components/AutoTest.vue, src/components/AutoTestSet.vue, src/components/AutoTestStep.vue, src/components/AutoTestSuite.vue, src/components/IPythonViewer.vue, src/pages/Submission.vue
* Fix confirmation message of the AssignmentState button on an LMS instance.
* Make Continuous Feedback visible to students before assignment is done.
* Make AutoTest tests less flaky.
* Fix AutoTest permission message.
* Fix error if feedback isn't set.
* Fix loadingInner on submission page.
* Fix weird AutoTestRun reloading bug where the results would constantly disappear and appear again.
=> Release hotfix JungleJoy.1.2

src/components/AutoTestStep.vue, src/components/SubmissionNavBar.vue
* Fix `canViewOutput` condition
* Fix `canViewSubstepOutput` check
* Fix `curUserId` prop on SubmissionNavBar
The check if `curSub` was empty was the wrong way around.
=> Release hotfix JungleJoy.4.1

cypress/integration/tests/rubric-viewer.spec.js, psef/lti.py, src/components/GradeViewer.vue, src/components/RubricViewer.vue, src/components/RubricViewerContinuousRow.vue, src/components/RubricViewerNormalRow.vue, src/models/rubric.js
* The "Mentor" role of LTI users is now ignored, rather than giving them the same permissions as TAs.
* Fix padding on the rubric row descriptions in the RubricViewer.
* Fix boundary of the lock popovers in the RubricViewer.
* Lock lock icon in place in the RubricViewer.
=> Release version Knoet.2.2

.github/workflows/backend.yml, cypress/integration/tests/rubric-editor.spec.js, cypress/integration/tests/rubric-viewer.spec.js, cypress/support/commands.js, src/components/AutoTestState.vue, src/components/GradeViewer.vue, src/main.js, src/models/rubric.js, src/store/modules/submissions.js, test/unit/specs/rubrics.spec.js, test_data/test_auto_tests/no_continuous.json, test_data/test_auto_tests/single_cat_two_items.json
* Add tests for the fixes in #1269.
* Only show "No grade calculation" message in the rubric viewer lock popover when the user has permission to view the AutoTest details.
* Fix issue storing rubric results after loading submissions by user.
* Show an ellipsis in the rubric max points in the grade viewer when the rubric result hasn't loaded yet.
* Fix AutoTest timers: due to the changes to how dates are represented the timers would always display `00:00`.
=> Test rubric editor when user can't view AutoTest

manage.py, src/components/SubmissionList.vue, test/unit/specs/SubmissionList.spec.js
Because we used a `Set` to count the number of unique names of students in a submission list, the count would be too low when there were students with the same name. Simply returning the length of the list of submissions should work now that the SubmissionList is really a list of all different users that have uploaded work to this assignment.
DEV-122 #close
=> [DEV-122] Fix student count in submission list

src/components/UsersManager.vue, src/components/WebhookInstructions.vue, src/style.less
`<code>` elements did not have the `white-space: pre-wrap` CSS property set, meaning that multiple consecutive wthitespaces would be collapsed, which was annoying in AutoTest commands where whitespace is significant... This PR changes sets that property on all `<code>` elements and fixes the places where this would cause a difference with how it was rendered previously.
DEV-87 #done
=> [DEV-87] Render all whitespace in all <code> elements

cypress/integration/tests/submission.spec.js, src/components/GradeViewer.vue, src/components/RubricViewer.vue, src/components/RubricViewerContinuousRow.vue, src/components/RubricViewerNormalRow.vue
Whenever a rubric result changed in the store (e.g. because its submission changed, or the AutoTest results updated it) it was set as the current result in the RubricViewer, discarding any changes that were made. This changes that so we now keep the changes that were made and apply those to the store result to get the current state.
Blocked by #1259 as this is based on that PR
DEV-88 #finished
=> [DEV-88] Do not discard changed rubric viewer when saving general feedback

docs/about/changelog.rst, src/components/CodeViewer.vue, src/components/DiffViewer.vue, src/components/FileViewer.vue, src/components/HtmlViewer.vue, src/components/IPythonViewer.vue, src/components/ImageViewer.vue, src/components/MarkdownViewer.vue, src/components/PdfViewer.vue, src/main.js, src/store/modules/code.js, test/unit/specs/DiffViewer.spec.js, test/unit/specs/IPythonViewer.spec.js
This makes each viewer component easier, as they do not need to handle async state. This also fixes a bug where nothing would be shown on empty markdown files.
=> Move loading of code to FileViewer component

cg_broker/api.py, psef/v1/about.py, psef_test/requests_stubs.py, psef_test/test_about.py
This is useful to make sure the instance is still able and allowed to communicate with the broker. If the instance is no longer able to do that AutoTest runs will silently not be started, resulting in a degraded service. This does make the health route a bit slower, but I think it is worth it for the extra security.
=> Add a check to see if we can reach the broker to the health route

config.py, psef/files.py, psef/v1/about.py, psef_test/test_about.py
This checks that we have enough space available in all directories we use for
writing. As we currently run all CodeGrade instance on a single disk volume it
is not really necessary to check each directory individually but it doesn't hurt
either.
=> Add a minimum amount of free space check to the health route

cg_broker/templates/macros/jobs_table.j2
We passed `formatted_created_at`, but with the update of bootstrap vue (I think)
this was changed to `formattedCreatedAt` in the front-end.
=> Fix the `sortBy` parameter used by the broker

cg_broker/api.py, cg_broker/models.py
Fix creating a job in the broker in finished state, earlier we tried to set
`state` after creating the job, however as the default value for `_state` wasn't
yet set the `_set_state` function crashed. Now we make it possible to set an
initial state using the `__init__` method.
DEV-185 #done
=> [DEV-185] Fix creating job in finished state

psef/tasks.py
This task also contacts the broker, so we should retry it if the requests to the
broker fail.
DEV-187 #done
=> [DEV-187] Retry adjust amount of runners in broker

src/store/modules/user.js
Unlike the verifyLogin action in the user store, the login action does
not add the logged in user to the users store. This causes an error on
pages that do not explicitly load users, such as on the manage
assignment page, where the submission uploader shows the name of the
logged in user by default.
=> Fix login action in user store

psef/models/lti_provider.py, psef/models/work.py, psef_test/test_submissions.py
If you deleted the newest submission of a test student while there was a older
submission the celery task to passback the grade failed. This PR moves all
filtering of the test student from passing back into a single method on the
LTIProvider.
=> [DEV-189] Fix error when deleting submission by test student

psef/v1/code.py, psef_test/test_code.py, src/utils/typed.ts
We did not account for the new way of deleting files (by only setting a flag) in the code that checks if a directory has children, so we would not treat files whose `deleted` flag was set as such. This fixes that and adds a test that we can only delete directories if all their children are deleted.
=> Fix deleting directory with deleted files

docs/about/changelog.rst, src/components/FeedbackOverview.vue
If you place a comment on your own submission as a student the badge of the feedback overview increments, however when you go to this overview the you are presented with the message "The feedback is not yet available.".
We used to determine when to show the message based on the permissions of a user, but now that students can place comments themselves they always have permission to see some comments. So now we always show feedback that we get back from the server, and only show the message when we've gotten nothing _and_ the student does not have permission to see feedback before the assignment is "done".
DEV-152 #done
=> DEV-152 Always show students' own comments in feedback overview

docs/about/changelog.rst, psef/auto_test/__init__.py, requirements.txt
The url query was invalid (it used a ? instead of a &). We now build the url
using `furl`, which ensures that it is always exactly as wanted.
=> Fix URL generation for getting more work

docs/about/changelog.rst, src/components/InnerIPythonViewer.vue, src/utils/ipython.ts, test/unit/specs/IPythonViewer.spec.js
We received an error that `join` is not a method on the output text of
an execute_result cell output. We always expected it to be a list of
strings, but it turns out that it is also sometimes just a string.
=> Fix ipython execute_result output

src/pages/Submissions.vue
On a medium screen we would try to fit 3 buttons next to each other, but
this wasn't giving them enough space to render their labels on a single
line on screens just a bit larger than small screens. This makes the
buttons 40% of the available width, up to a minimum size that leaves
them enough space to draw their labels on a single line.
Before
After
DEV-169 #done
=> DEV-169 Improve student buttons on submissions page

.github/scripts/run_backend_tests.bash, migrations/env.py, psef_test/conftest.py, psef_test/migrations/__init__.py, psef_test/migrations/migration_bef732f2f4ac/__init__.py, psef_test/migrations/migration_bef732f2f4ac/setup_upgrade.sql, psef_test/migrations/migration_e9b4a9fe0b85/__init__.py, psef_test/migrations/migration_e9b4a9fe0b85/setup_downgrade.sql, psef_test/migrations/migration_e9b4a9fe0b85/setup_upgrade.sql, psef_test/test_migrations.py
You can add tests by adding a new file in the `psef_test/migrations/` directory. This test can either be a directory or a simple python file. If imported the module/file should expose two classes `TestUpgrade` and `TestDowngrade`. Each class has to define some methods, see the committed migration test as example. If it is a directory the directory can also contain `setup_upgrade.sql` and `setup_downgrade.sql` which will be executed before respectively the upgrade and downgrade tests.
DEV-220 #finished
=> [DEV-220] Make it possible to add tests for migrations

docs/about/changelog.rst, src/components/AutoTestSuite.vue
We used the values on the AutoTestSuite model before this, but those would not be updated when the rubric is changed. Now we always get the rubric rows from the store,  ensuring we use the correct rubric category headers.
DEV-146 #done
=> DEV-146 Use rubric rows from the store in AutoTestSuite

src/components/LtiProviderSetup/BrightspaceSetup.vue
Brightspace wasn't always spelled with a capital and we didn't update the
provider after we updated the information.
=> Improve Brightspace wizard

docs/about/changelog.rst, src/components/SubmissionList.vue, src/pages/Submission.vue, test/unit/specs/Submission.spec.js
The category switched because `defaultCat` was a computed property which
changed after deleting the final comment on a submission from the
feedback overview, when the feedback overview was the default category.
With this change the default category is set only once per submission,
so it will not change after the initial page load anymore.
DEV-175 #done
=> DEV-175 Fix submission page category switching after initial load

docs/about/changelog.rst, src/components/AutoTestSet.vue, src/components/AutoTestStep.vue
On some screen sizes (slightly above `1200px` wide) the AutoTest suite
tables were drawn outside of the card sometimes.
At first I thought this happened because the `colspan` attributes on the
collapsed table rows were wrong. They were always set to 5, but when no
result is present the rest of the table has only 4 columns. This did not
fix the problem, though.
In the end I found that it is caused by `<code>` tags containing long
unbreakable words. I tried to address the problem in two ways:
* Increase the minimum screen size required to render the test suites in
two columns by 25%. Before the split was at `1200px`, so this is now
`1500px`. This means that a single-column suite can now become quite
wide, but I think it's better than the alternative of two columns
becoming very narrow on …
=> Fix AutoTest suite table rendering

docs/about/changelog.rst, src/components/AnalyticsRubricStats.vue
Adds some more information about the rubric category to the tooltips in the rubric analytics graphs. This includes:
* An `(AutoTest)` label appended to the category title in the tooltip.
* The maximum amount of points that can be scored in the rubric category. This is currently only displayed in the tooltip, but it might be nice to visualise it in the graph. Something like the second category in the mockup below (the average score is 1.5 out of a maximum of 2 points). But I think that is something for later.
DEV-157 #done
=> DEV-157 Add more rubric category information to rubric analytics tooltips

psef/mail_templates/base.j2
We should still test this in a few email clients.
DEV-176 #done
=> DEV-176 Remove link from logo in email template

README.md
We don't use version anymore, so the semVer badge did not make sense. Of course we don't want to just remove a badge, so I've replaced it with the latest release date because
* that's obviously very useful to know ;-)
* it will be green most of the time because we release frequently
* it fits nicely in the spot where the semver badge used to be, right after the latest release name
=> Replace the semVer badge with the latest release date

docs/about/changelog.rst, src/models/auto_test.js
The new Unit Test step always had a green checkmark as its state, even when none of the tests passed. This changes its behaviour to be the same as the Capture Points test, i.e. a green checkmark only when all tests passed, a black tilde if some but not all tests passed, and a red cross when all tests failed or you achieved 0 points in some other way.
DEV-243 #finished
=> DEV-243 Use capture points step state icons for unit test step

src/components/SubmissionList.vue, src/components/UsersManager.vue
There were still some places where, if an error occurred, we would only log it and do nothing else. Those places were:
* Changing a user's role within a course.
* Changing the assignee of a submission.
While we still haven't got a great solution for them, I think showing a toast with the error message received from the backend is already much better than showing the user nothing.
=> Stop silently ignoring errors

docs/about/changelog.rst, src/components/PeerFeedbackOverview.vue
This changes the badges containing the number of comments in the PeerFeedbackOverview component. The badges now always only contain the number of comments on the latest submission of the reviewed student. If the logged in student has given feedback to older submissions of their subject, the badge will get `variant="warning"` and gets a popover on hover. If the logged in user hasn't given any peer feedback to one of their subjects, the badge will be `variant="secondary"`. Lastly, if the user has given peer feedback, and all of their peer feedback was on the latest submission, the badge will be `variant="primary"`.
DEV-242 #done
=> DEV-242 Make # of Peer Feedback comments more clear

.gitignore, build/webpack.prod.conf.js, src/main.js, src/utils/typed.ts
This changes two things:
1. It builds a static file that contains the commit hash of the latest front-end
version of CodeGrade available. This fixes the problem when the backend was
already restarted but the frontend was still building, in this case the toast
was visible but reloading didn't actually update the frontend. This also reduces
some of the load on the backend.
2. When the request fails for whatever reason we used to show the toast, now we
never show the toast as the most common case is that there is actually no new
version available.
=> Improve the "Upgrade available" toasts

cg_sqlalchemy_helpers/__init__.py, cg_sqlalchemy_helpers/types.py, psef/models/auto_test.py
We now reuse the correct way to determine which submissions to consider (latest
only). As this makes the query slower I also merged the three separate queries
into a single one, which should give the db engine some options for
optimizations.
=> Fix calculating metadata for broker

src/components/AssignmentGeneralSettings.vue
Many LTI 1.1 providers do not allow bonus points, and therefore the `maxGrade`
attribute should not been provided.
=> Fix setting general assignment settings for LTI 1.1 assignments

src/lti_providers.ts
In the backend we used the tag "BrightSpace" for the LMS while in the
frontend we expected it to be "Brightspace" (no capital S), so we
couldn't find it and it would throw an error.
This adds a new "tag" attribute to LTI1p1 providers to map the backend
tags to the correct LTIProvider instance.
=> Fix getting the Brightspace LTI provider in the frontend

docs/about/changelog.rst, src/cg-math/index.js
This makes it easier to add links inside markdown blocks.
=> Expand inline links in markdown viewers

src/components/GroupManagement.vue
The error occurred because in the error case of the `this.group.getMemberStates(...).then` we tried to get the `data` attribute of the error, which does not exist. So we set `this.memberStates` to `undefined`, which causes an error that breaks the reload timer loop.
With this change we only overwrite `this.memberStates` if we got a valid response.
=> Fix error when group member states cant be loaded

src/components/InnerIPythonViewer.vue
Removing `overflow-x: hidden` from IPython `.output-cell .code` fixes
the double scrollbars on Firefox and Chrome. I don't think the
`overflow-x` could be very important, because the code viewer already
wraps code, so there would never be any overflow anyway.
TODO:
DEV-264 #done
=> DEV-264 Fix double scrollbars in IPython viewer

src/components/SnippetManager.vue, test/unit/specs/SnippetManager.spec.js
This also fixes an error that occurred when pressing <kbd>Enter</kbd> in the snippets search input, because we bound a nonexisting handler.
=> Store snippets filter in the URL query params

cg_sqlalchemy_helpers/types.py, psef/models/assignment.py, psef_test/test_peer_feedback.py
If we had an assignment that already had a submission by the test student before
peer feedback was enabled (or if the settings of the PF was adjusted after there
was a submission by the test student) we didn't filter this user out when doing
the assignments. This PR fixes that behavior, and it makes sure we don't count
submissions by the test student when determining if we can do the initial
division.
This change also makes use of the same way to actually retrieve the users with
submissions. This method is incorrect for group assignments (which are not
support in combination with peer feedback), but is quicker as it does less
logic.
=> Make sure test students are never used as peer feedback

src/pages/Submission.vue
We always need this information (for peer feedback assignment of course) to
determine if we can give feedback on the current submission. Previously this was
only done in the `PeerFeedbackByUser` component, but doesn't always render
before the first code viewers show up.
=> Always load peer feedback connections on submission page 

cg_sqlalchemy_helpers/types.py, docs/about/changelog.rst, docs/guides/creating-a-canvas-assignment.rst, docs/guides/creating-an-assignment.rst, docs/guides/creating-an-open-edx-assignment.rst, docs/guides/getting-started-with-codegrade-in-open-edx.rst, docs/guides/getting-started-with-codegrade.rst, docs/guides/setup-password.rst, npm-shrinkwrap.json, psef/lti/v1_1.py, psef/models/assignment.py, psef_test/conftest.py, psef_test/test_lti.py, psef_test/test_peer_feedback.py, src/cg-math/index.js, src/components/GroupManagement.vue, src/components/InnerIPythonViewer.vue, src/components/LtiProviderSetup/CanvasSetup.vue, src/components/SnippetManager.vue, src/lti_providers.ts, src/pages/Submission.vue, test/unit/specs/SnippetManager.spec.js
* Expand inline links in markdown viewers (#1448)
* Fix error when group member states cant be loaded (#1449)
* Fix double scrollbars in IPython viewer (#1450)
* Fix getting the Brightspace LTI provider in the frontend (#1451)
* Add support for Open edX (#1452)
* Remove Canvas advanced options section (#1453)
* Store snippets filter in the URL query params (#1454)
* Make sure test students are never used as peer feedback (#1455)
* Always load peer feedback connections on submission page (#1456)
=> Release hotfix Mosaic.1.2

psef/lti/v1_1.py
This makes issues with parsing (i.e. "New LTI Role") easier to debug.
=> Add log call when parsing LTI 1.1 roles

cypress/integration/tests/file-viewer.spec.js, cypress/support/commands.js, src/components/FeedbackReply.vue, src/components/FloatingFeedbackButton.vue, src/components/ImageViewer.vue, src/components/MarkdownViewer.vue, src/components/PdfViewer.vue
The feedback was not scrollable because the `.Pane`s in the components using the `FloatingFeedbackButton` all had `overflow: visible` instead of `auto`.
=> Fix feedback in the FloatingFeedbackButton not being scrollable

src/components/ImageViewer.vue
Adds a checkerboard background pattern to the image viewer:
I first tried to do it with a CSS gradient, but that was very glitchy at different zoom levels, because it was rendering half squares and stitching them together. So this uses a very simple svg containing only 2 rects to achieve a better result.
=> Add checkerboard background to image viewer

src/components/CodeViewer.vue
In Google Chrome in incognito mode the language store would return `undefined`
when getting the language, which we would then store in `selectedLanguage`,
but in the rest of the component we check with `this.selectedLanguage != null`
to make sure we already loaded the language, and of course `null ==
undefined`. This PR fixes that behavior by also checking the return from
`getItem` against `null` with eqeq and not eqeqeq. Furthermore, this also adds
a catch clause on the call to `getItem` to make sure we never crash/freeze the
page because of that function rejecting.
=> Fix the CodeViewer when loading settings fails
